application:
  port: 8000
  hmac_secret: "very_secret_token_000000_000000_0000000_00000000000_000000000_00000000"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "patternsaver"
email_client:
  base_url: "localhost"
  api_key: "eb2f873e5d21e3578ab95af78b52385f"
  api_token: "CHANGE_ME"
redis_uri: "redis://127.0.0.1:6379"
